#!/usr/bin/python

import sys
import string

def normalize_line(line):
    line = line.strip()
    (arch,comp,pkg,bins) = line.split("|")
    bins = bins.split(",")
    bins.sort()
    return "%s|%s|%s|%s" % (arch, comp, pkg, ",".join(bins))

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print "need two files"
        sys.exit(1)

    old = set()
    new = set()

    for l in map(normalize_line, open(sys.argv[1])):
        old.add(l)
    for l in map(normalize_line, open(sys.argv[2])):
        new.add(l)

    print "new:"
    for line in set(new - old):
        print line

    print "\nremoved:"
    for line in set(old - new):
        print line
